# The name of this app. Must be unique within a project.
name: app
type: 'nodejs:22'

web:
  commands:
    start: npm start
mounts:
  'web/uploads':
    source: local
    source_path: uploads

disk: 2048